// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationEFCore10;

#nullable disable

namespace MigrationEFCore10.Migrations
{
    [DbContext(typeof(MetigatorAcademyContext))]
    partial class MetigatorAcademyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SectionId")
                        .HasName("PK__Enrollme__0ACBDB1E387E83EF");

                    b.HasIndex(new[] { "SectionId" }, "idx_enrollments_section_id");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("MigrationEFCore10.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3214EC0755FA43A5");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MigrationEFCore10.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Instruct__3214EC07C60CC125");

                    b.HasIndex("OfficeId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("MigrationEFCore10.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Offices__3214EC07C614CF32");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("MigrationEFCore10.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Fri")
                        .HasColumnType("bit")
                        .HasColumnName("FRI");

                    b.Property<bool>("Mon")
                        .HasColumnType("bit")
                        .HasColumnName("MON");

                    b.Property<bool>("Sat")
                        .HasColumnType("bit")
                        .HasColumnName("SAT");

                    b.Property<bool>("Sun")
                        .HasColumnType("bit")
                        .HasColumnName("SUN");

                    b.Property<bool>("Thu")
                        .HasColumnType("bit")
                        .HasColumnName("THU");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Tue")
                        .HasColumnType("bit")
                        .HasColumnName("TUE");

                    b.Property<bool>("Wed")
                        .HasColumnType("bit")
                        .HasColumnName("WED");

                    b.HasKey("Id")
                        .HasName("PK__Schedule__3214EC07B6CD2009");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("MigrationEFCore10.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Sections__3214EC07C1F9A3ED");

                    b.HasIndex(new[] { "CourseId" }, "idx_sections_course_id");

                    b.HasIndex(new[] { "InstructorId" }, "idx_sections_instructor_id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("MigrationEFCore10.SectionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__SectionS__3214EC07BEF980A6");

                    b.HasIndex("SectionId");

                    b.HasIndex(new[] { "ScheduleId" }, "idx_section_schedules_schedule_id");

                    b.ToTable("SectionSchedules");
                });

            modelBuilder.Entity("MigrationEFCore10.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC07F98B1C75");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.HasOne("MigrationEFCore10.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Secti__4AB81AF0");

                    b.HasOne("MigrationEFCore10.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Stude__49C3F6B7");
                });

            modelBuilder.Entity("MigrationEFCore10.Instructor", b =>
                {
                    b.HasOne("MigrationEFCore10.Office", "Office")
                        .WithMany("Instructors")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__Offic__3B75D760");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("MigrationEFCore10.Section", b =>
                {
                    b.HasOne("MigrationEFCore10.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Sections__Course__3E52440B");

                    b.HasOne("MigrationEFCore10.Instructor", "Instructor")
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK__Sections__Instru__3F466844");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("MigrationEFCore10.SectionSchedule", b =>
                {
                    b.HasOne("MigrationEFCore10.Schedule", "Schedule")
                        .WithMany("SectionSchedules")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__SectionSc__Sched__44FF419A");

                    b.HasOne("MigrationEFCore10.Section", "Section")
                        .WithMany("SectionSchedules")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__SectionSc__Secti__440B1D61");

                    b.Navigation("Schedule");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("MigrationEFCore10.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("MigrationEFCore10.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("MigrationEFCore10.Office", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("MigrationEFCore10.Schedule", b =>
                {
                    b.Navigation("SectionSchedules");
                });

            modelBuilder.Entity("MigrationEFCore10.Section", b =>
                {
                    b.Navigation("SectionSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
